### ISSUE TITLE
App is down

### ISSUE THREAD

**Issue by agent2397** [rrnarayan1/omni-crosswords#16] opened 2024-05-26 06:32 UTC
When you open the app it immediately closes. Might be a server issue?

I’ve tried deleting the app and reinstalling. Also have tried on another device. 

Thank you for creating and supporting this app 🙌

**Comment by AmyAmeliaLee** [comment] 2024-05-26 15:07
Sadly I can confirm this. It seems that the functionality behind uploading/updating the puzzles may be causing this.

**Comment by rrnarayan1** [comment] 2024-06-13 22:19
This is because of a puzzle metadata issue. When parsing the puzzle to display the list view, the app could crash. I will leave this issue open to address that issue by failing more gracefully.

**Comment by rrnarayan1** [comment] 2024-07-01 05:11
addressed in b859987

**Closed by rrnarayan1** 2024-07-01 05:11 UTC
